using System.IO;
using Jane.App.Tray;

namespace Jane.App.Tests;

/// <summary>
/// The executable's icon, and keeping it identical to the tray's.
/// </summary>
/// <remarks>
/// <para>
/// Jane.exe shipped with the stock .NET icon, because the project declared no
/// <c>ApplicationIcon</c> and there was no image file anywhere in the repository to declare. The
/// tray icon was never a file -- <see cref="TrayIconArtwork"/> draws it in memory at start-up, on
/// purpose, so that it and the pill cannot drift apart.
/// </para>
/// <para>
/// MSBuild needs the executable's icon as a file at compile time, which that design cannot supply.
/// So <c>jane.ico</c> is committed, generated by the same code, and this test regenerates it and
/// compares the bytes. Committing a second drawing of the same mark would have reintroduced
/// exactly the drift the generator exists to prevent; this way the file is a build artefact that
/// happens to live in git, and it cannot silently diverge.
/// </para>
/// </remarks>
public sealed class ApplicationIconTests
{
    private static string IconPath => PackagingTests.FindRepoFile(Path.Combine("src", "Jane.App", "jane.ico"));

    [Fact]
    public void TheCommittedIconMatchesWhatTheTrayDraws()
    {
        using var regenerated = new MemoryStream();
        TrayIconArtwork.Write(regenerated, TrayIconArtwork.ApplicationSizes);

        var committed = File.ReadAllBytes(IconPath);

        Assert.True(
            regenerated.ToArray().AsSpan().SequenceEqual(committed),
            "src/Jane.App/jane.ico is out of date with TrayIconArtwork. Regenerate it rather than "
            + "editing it by hand -- the point of generating it is that the exe icon and the tray "
            + "icon cannot drift.");
    }

    [Fact]
    public void TheIconCarriesEverySizeWindowsAsksFor()
    {
        var committed = File.ReadAllBytes(IconPath);

        // ICONDIR: reserved(2), type(2), count(2). Type 1 is an icon; 2 would be a cursor.
        Assert.Equal(0, BitConverter.ToUInt16(committed, 0));
        Assert.Equal(1, BitConverter.ToUInt16(committed, 2));
        Assert.Equal(TrayIconArtwork.ApplicationSizes.Length, BitConverter.ToUInt16(committed, 4));
    }

    [Fact]
    public void TheLargeSizesExplorerUsesArePresent()
    {
        // 256 is what Explorer's extra-large view and the Alt-Tab switcher reach for. Without it
        // Windows upscales the 64px entry and the mark goes soft exactly where it is biggest.
        Assert.Contains(256, TrayIconArtwork.ApplicationSizes);
        Assert.Contains(128, TrayIconArtwork.ApplicationSizes);
    }

    [Fact]
    public void TheProjectActuallyPointsAtIt()
    {
        var project = File.ReadAllText(
            PackagingTests.FindRepoFile(Path.Combine("src", "Jane.App", "Jane.App.csproj")));

        // Generating the file and then not referencing it is the failure mode this catches: the
        // icon looks committed and correct, and the exe still ships with the .NET default.
        Assert.Contains("<ApplicationIcon>jane.ico</ApplicationIcon>", project);
    }
}
