<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Jane.Core\Jane.Core.csproj" />
    <ProjectReference Include="..\..\src\Jane.Speech\Jane.Speech.csproj" />
    <ProjectReference Include="..\..\src\Jane.Llm\Jane.Llm.csproj" />
    <ProjectReference Include="..\..\src\Jane.Windows\Jane.Windows.csproj" />
    <ProjectReference Include="..\..\src\Jane.Bench\Jane.Bench.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
